AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Inventory backend with DynamoDB, S3 for images, and Node.js Lambdas

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        TABLE_NAME: !Ref InventoryTable
        BUCKET_NAME: !Ref ImageBucket
        DEFAULT_PAGE_SIZE: 50

Resources:
  # DynamoDB Table
  InventoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: gsi1_pk
          AttributeType: S
        - AttributeName: gsi1_sk
          AttributeType: S
        - AttributeName: gsi2_pk
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: gsi1_pk
              KeyType: HASH
            - AttributeName: gsi1_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: gsi2_pk
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  # S3 Bucket for Product Images
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3000

  # API Gateway (Implicitly created by Events, but we can configure it if needed)

  # Functions
  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/src/
      Handler: list.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InventoryTable
      Events:
        ListProducts:
          Type: Api
          Properties:
            Path: /products
            Method: get

  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/src/
      Handler: create.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InventoryTable
      Events:
        CreateProduct:
          Type: Api
          Properties:
            Path: /products
            Method: post

  GetProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/src/
      Handler: get.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InventoryTable
      Events:
        GetProduct:
          Type: Api
          Properties:
            Path: /products/{id}
            Method: get

  UpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/src/
      Handler: update.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InventoryTable
      Events:
        UpdateProduct:
          Type: Api
          Properties:
            Path: /products/{id}
            Method: put

  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/src/
      Handler: delete.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InventoryTable
        - S3CrudPolicy:
            BucketName: !Ref ImageBucket
      Events:
        DeleteProduct:
          Type: Api
          Properties:
            Path: /products/{id}
            Method: delete

  GetUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/src/
      Handler: upload_url.handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ImageBucket
      Events:
        GetUploadUrl:
          Type: Api
          Properties:
            Path: /upload-url
            Method: post

  GetImageUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/src/
      Handler: get_image_url.handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ImageBucket
      Events:
        GetImageUrl:
          Type: Api
          Properties:
            Path: /image-url
            Method: post

  # Explicit OPTIONS handlers if needed by API Gateway to pass checks,
  # though usually the 'Cors' property on API or Function can handle it.
  # The lambda code itself handles OPTIONS so we just need the traffic to reach it.
  # We can add an 'Options' event to each path or a catch-all.
  # For simplicity, we rely on the implementation handling it if it receives the request.
  # To ensure API Gateway lets it through:
  
Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  InventoryTable:
    Description: "DynamoDB Table"
    Value: !Ref InventoryTable
  ImageBucket:
    Description: "S3 Bucket for Images"
    Value: !Ref ImageBucket
